---
- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ zsh_omz_root }}"
    version: "{{ zsh_omz_version }}"

- name: Install omz plugins
  ansible.builtin.git:
    repo: "https://github.com/{{ item.repo }}.git"
    dest: "{{ zsh_omz_root }}/custom/plugins/{{ item.repo | basename }}"
    version: "{{ item.version }}"
  loop: "{{ zsh_omz_plugins }}"

- name: Install powerlevel prompt
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_omz_root }}/custom/themes/powerlevel10k"
    version: "{{ zsh_p10k_version }}"

- name: Set login shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
