##########################
# Packages and Symlinks
##########################

# Ubuntu - Debian
apt_packages:
  - zsh
  - tmux
  - exa
  - bat
  - fd-find
  - ripgrep
  - git
symlinks:
  bat: /usr/bin/batcat
  fd: /usr/bin/fdfind

# MacOS - Darwin
ports:
  - zsh
  - tmux
  - exa
  - bat
  - fd
  - ripgrep
  - git
  - gnutar

##########################
#   Dotfiles to Copy
##########################
dotfiles:
  - .zshrc
  - .tmux.conf
  - .tmux.conf.local
  - .p10k.zsh

##########################
#   Zsh + Oh-My-Zsh
##########################
omz_version: HEAD
omz_root: "{{ home_dir }}/.oh-my-zsh"
p10k_version: 35833ea15f14b71dbcebc7e54c104d8d56ca5268
omz_plugins:
  - repo: "zsh-users/zsh-autosuggestions"
    version: a411ef3e0992d4839f0732ebeb9823024afaaaa8
  - repo: "zsh-users/zsh-syntax-highlighting"
    version: db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e
  - repo: "zsh-users/zsh-completions"
    version: 67921bc12502c1e7b0f156533fbac2cb51f6943d
  - repo: "wfxr/forgit"
    version: d582f2aa0b5bf7948d78aca05c55a974e68f4884

##########################
#   Golang + Go Tools
##########################
go_version_target: 1.22.2

go_platform: "{{ ansible_os_family | lower | regex_replace('darwin', 'macos') | regex_replace('debian', 'linux') }}"
go_arch: "{{ ansible_machine | lower | regex_replace('aarch64', 'arm64') }}"
go_tarball: "go{{ go_version_target }}.{{ go_platform }}-{{ go_arch }}.tar.gz"
go_tarball_url: "https://golang.org/dl/{{ go_tarball }}"

go_packages:
  run: github.com/amonks/run/cmd/run@v1.0.0-beta.24
  glow: github.com/charmbracelet/glow@latest
  mods: github.com/charmbracelet/mods@latest
  skate: github.com/charmbracelet/skate@latest
  gum: github.com/charmbracelet/gum@latest
  freeze: github.com/charmbracelet/freeze@latest

golang_checksums:
  '1.21.8':
    linux:
      arm64: 3c19113c686ffa142e9159de1594c952dee64d5464965142d222eab3a81f1270
  '1.22.2':
    linux:
      arm64: 36e720b2d564980c162a48c7e97da2e407dfcc4239e1e58d98082dfa2486a0c1
      amd64: 5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17
    darwin:
      arm64: 660298be38648723e783ba0398e90431de1cb288c637880cdb124f39bd977f0d
