---
- name: Configure system
  tags: [stable, base]
  hosts: 127.0.0.1
  vars_files:
    - config_vars.yml
  roles:
    - shell
  vars:
    clean: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure go and python
  tags: [stable, dev]
  hosts: 127.0.0.1
  vars_files:
    - config_vars.yml
  roles:
    - golang
    - python
    - cleanup
  vars:
    clean: false
    go_version_target: 1.22.2
    python_version_target: 3.12.2
  ignore_errors: "{{ ansible_check_mode }}"
