---
- name: Configure system
  tags: [stable, system]
  hosts: localhost
  vars_files:
    - config_vars.yml
  roles:
    - shell
    - golang
    - python
    - hashi
    - cleanup
  vars:
    clean: false
    go_version_target: 1.22.2
    python_version_target: 3.12.2
