---
- name: Copy dotfile to the home directory -- {{ dotfile_name }}
  ansible.builtin.copy:
    src: "{{ toolbox_path }}/config_files/{{ dotfile_name }}"
    dest: "{{ home_dir }}/{{ dotfile_name }}"
    backup: true
    mode: '0644'
  register: copy_result

- name: Print the backup file path
  ansible.builtin.debug:
    msg: "Backup file path: {{ copy_result }}"

- name: Create the backup directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ home_dir }}/dotfile_backups"
    state: directory
    mode: '0755'

- name: Move the backup of previous version to the backup directory
  ansible.builtin.copy:
    src: "{{ copy_result.backup_file }}"
    dest: "{{ home_dir }}/dotfile_backups/{{ dotfile_name }}.bak"
    remote_src: true
    mode: '0644'
  when: copy_result.backup_file is defined

- name: Remove the backup file
  ansible.builtin.file:
    path: "{{ copy_result.backup_file }}"
    state: absent
  when: copy_result.backup_file is defined
