---
- name: Run FZF uninstall script
  ansible.builtin.command: "{{ ansible_env.HOME }}/.fzf/uninstall"
  args:
    removes: "{{ ansible_env.HOME }}/.fzf/bin/fzf"
  when: clean
  ignore_errors: "{{ ansible_check_mode }}"

- name: Download latest FZF via git
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1
    update: true
    version: master
  ignore_errors: "{{ ansible_check_mode }}"

- name: Run fzf installation script
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.fzf/install"
    creates: "{{ ansible_env.HOME }}/.fzf/bin/fzf"
  ignore_errors: "{{ ansible_check_mode }}"
