---
- name: Run FZF uninstall script
  ansible.builtin.command: "{{ home_dir }}/.fzf/uninstall"
  args:
    removes: "{{ home_dir }}/.fzf/bin/fzf"
  when: clean

- name: Download latest FZF via git
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ home_dir }}/.fzf"
    depth: 1
    update: false
    version: master

- name: Run fzf installation script
  ansible.builtin.command:
    cmd: "{{ home_dir }}/.fzf/install"
    creates: "{{ home_dir }}/.fzf/bin/fzf"
