---
- name: Root installation tasks
  when: ansible_os_family == 'Debian'
  become: true
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      check_mode: false
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Create symbolic links
      ansible.builtin.file:
        src: "{{ item.value }}"
        dest: "{{ item.value | dirname }}/{{ item.key }}"
        state: link
        force: true  # This will replace the link if it already exists
      loop: "{{ symlinks | dict2items }}"
      ignore_errors: "{{ ansible_check_mode }}"

- name: Macports port installs
  community.general.macports:
    name: "{{ item }}"
    state: present
  loop: "{{ ports }}"
  when: ansible_os_family == 'Darwin'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Oh My Zsh Install
  ansible.builtin.include_tasks: omz.yml
  when: omz_install
  ignore_errors: "{{ ansible_check_mode }}"

- name: FZF Install
  ansible.builtin.include_tasks: fzf.yml
  when: fzf_install
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy dotfiles
  ansible.builtin.include_tasks: dotfile.yml
  loop: "{{ dotfiles }}"
  loop_control:
    loop_var: dotfile_name
