---
- ansible.builtin.include_tasks: zsh.yml
- ansible.builtin.include_tasks: omz.yml
- ansible.builtin.include_tasks: p10k.yml
- ansible.builtin.include_tasks: fzf.yml
- name: Source zshrc
  ansible.builtin.shell: zsh -i -c "source ~/.zshrc"
  ignore_errors: "{{ ansible_check_mode }}"