---
- name: Ubuntu install packages with apt
  ansible.builtin.include_tasks: aptpackages.yml
  when: ansible_os_family == 'Debian'

- name: MacOS install ports with macports
  ansible.builtin.include_tasks: macports.yml
  when: ansible_os_family == 'Darwin'

- name: Oh My Zsh Install
  ansible.builtin.include_tasks: omz.yml
  when: omz_install
  ignore_errors: "{{ ansible_check_mode }}"

- name: FZF Install
  ansible.builtin.include_tasks: fzf.yml
  when: fzf_install
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy dotfiles
  ansible.builtin.include_tasks: dotfile.yml
  loop: "{{ dotfiles }}"
  loop_control:
    loop_var: dotfile_name
  ignore_errors: "{{ ansible_check_mode }}"
