---
- name: Ensure the parent dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Unarchive navi
  ansible.builtin.unarchive:
    remote_src: true
    src: 'https://github.com/denisidoro/navi/releases/download/v2.23.0/navi-v2.23.0-aarch64-unknown-linux-gnu.tar.gz'
    dest: '{{ ansible_env.HOME }}/.local/bin'
    creates: '{{ ansible_env.HOME }}/.local/bin/navi'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure the config parent dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/navi"
    state: directory
    mode: '0755'
  ignore_errors: "{{ ansible_check_mode }}"
