---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name:
      - build-essential
      - libffi-dev
      - python3-dev
      - python3-pip
      - python3-venv
      - libonig-dev
    state: present
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install ansible-navigator
  ansible.builtin.pip:
    name: ansible-navigator
    state: present
    executable: pip3
  ignore_errors: "{{ ansible_check_mode }}"
