---
- name: Install powerlevel prompt
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    version: 35833ea15f14b71dbcebc7e54c104d8d56ca5268
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable powerlevel theme
  ansible.builtin.file:
    src: ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k.zsh-theme
    state: link
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy powerlevel config
  ansible.builtin.copy:
    src: p10k.zsh
    dest: ~/.p10k.zsh
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
