---
- name: Check if the file exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/{{ config_dest }}"
  register: st

- name: Backup the original file
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/{{ config_dest }}"
    dest: "{{ ansible_env.HOME }}/{{ config_dest }}.bak"
    remote_src: true
    mode: '0644'
  when: st.stat.exists

- name: Copy the new file
  ansible.builtin.copy:
    src: "{{ config_src }}"
    dest: "{{ ansible_env.HOME }}/{{ config_dest }}"
    mode: '0644'
