version: "3.1"

services:
  charm:
    image: charmcli/charm:latest
    container_name: charm
    volumes:
      - charmdata:/data
    ports:
      - 35353:35353
      - 35354:35354
      - 35355:35355
      - 35356:35356
    restart: unless-stopped

volumes:
  charmdata: