##########################
#   Golang + Go Tools
##########################
go_version_target: 1.23.2

go_root: "/usr/local/go"
go_bin: "/usr/local/go/bin"
go_platform: "{{ ansible_os_family | lower | regex_replace('macos', 'darwin') | regex_replace('debian', 'linux') }}"
go_arch: "{{ ansible_machine | lower | regex_replace('aarch64', 'arm64') | regex_replace('x86_64', 'amd64') }}"
go_tarball: "go{{ go_version_target }}.{{ go_platform }}-{{ go_arch }}.tar.gz"
go_tarball_url: "https://golang.org/dl/{{ go_tarball }}"

go_packages:
  run: github.com/amonks/run/cmd/run@v1.0.0-beta.24

charm_packages:
  glow: github.com/charmbracelet/glow@latest
  mods: github.com/charmbracelet/mods@latest
  skate: github.com/charmbracelet/skate@latest
  gum: github.com/charmbracelet/gum@latest
  freeze: github.com/charmbracelet/freeze@latest
  vhs: github.com/charmbracelet/vhs@latest
  wishlist: github.com/charmbracelet/wishlist/cmd/wishlist@latest

golang_checksums:
  '1.23.2':
    linux:
      arm64: f626cdd92fc21a88b31c1251f419c17782933a42903db87a174ce74eeecc66a9
    darwin:
      arm64: d87031194fe3e01abdcaf3c7302148ade97a7add6eac3fec26765bcb3207b80f
  '1.21.8':
    linux:
      arm64: 3c19113c686ffa142e9159de1594c952dee64d5464965142d222eab3a81f1270
  '1.22.1':
    linux:
      amd64: aab8e15785c997ae20f9c88422ee35d962c4562212bb0f879d052a35c8307c7f
  '1.22.2':
    linux:
      arm64: 36e720b2d564980c162a48c7e97da2e407dfcc4239e1e58d98082dfa2486a0c1
      amd64: 5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17
    darwin:
      arm64: 660298be38648723e783ba0398e90431de1cb288c637880cdb124f39bd977f0d

##########################
#   Python + Pip
##########################
# Installation paths
pyenv_home: "{{ ansible_env.HOME }}"
pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
pyenv_install_shell: "zsh"

# Versions to install
pyenv_version: "v2.3.36"
pyenv_virtualenv_version: "v1.2.1"

# Python versions
pyenv_python311_version: "3.11.8"

# Python versions to install
pyenv_python_versions:
  - "{{ pyenv_python311_version }}"

# Set global pyenv version
pyenv_global: "{{ python_version_target }}"

python_build_deps:
  - build-essential 
  - libssl-dev 
  - zlib1g-dev
  - libbz2-dev 
  - libreadline-dev 
  - libsqlite3-dev
  - libncursesw5-dev 
  - libxml2-dev 
  - libxmlsec1-dev 
  - libffi-dev 
  - liblzma-dev