---
- name: Ensure alacritty config directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/alacritty"
    state: directory
    mode: "0755"
  tags: [apps]
- name: Link alacritty config
  ansible.builtin.file:
    src: "{{ toolbox_dir }}/config_files/apps/alacritty.toml"
    dest: "{{ home_dir }}/.config/alacritty/alacritty.toml"
    state: link
    force: true
    mode: "0644"
  tags: [apps]