omz_version: HEAD
omz_root: "{{ home_dir }}/.oh-my-zsh"
p10k_version: 35833ea15f14b71dbcebc7e54c104d8d56ca5268
omz_plugins:
  - repo: "zsh-users/zsh-autosuggestions"
    version: a411ef3e0992d4839f0732ebeb9823024afaaaa8
  - repo: "zsh-users/zsh-syntax-highlighting"
    version: db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e
  - repo: "zsh-users/zsh-completions"
    version: 67921bc12502c1e7b0f156533fbac2cb51f6943d
  - repo: "wfxr/forgit"
    version: d582f2aa0b5bf7948d78aca05c55a974e68f4884
