---
- name: Extract general dotfile config files from config_files
  ansible.builtin.find:
    paths: "{{ toolbox_dir }}/config_files/dotfiles"
    file_type: any
    hidden: true
  register: general_config_files

- name: Remove file if replacement is being linked
  ansible.builtin.file:
    path: "{{ home_dir }}/{{ item.path | basename }}"
    state: absent
  loop: "{{ general_config_files.files }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create symlinks for files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/{{ item.path | basename }}"
    state: link
    force: true
    mode: "0644"
  loop: "{{ general_config_files.files }}"
  