---
- name: Check for existing toolbox repo
  ansible.builtin.git:
    repo: "{{ dotfiles_toolbox_repo }}"
    dest: "{{ dotfiles_toolbox_dir }}"
    version: "{{ dotfiles_toolbox_version }}"
    clone: false
  register: toolbox_repo

- name: Clone toolbox
  ansible.builtin.git:
    repo: "{{ dotfiles_toolbox_repo }}"
    dest: "{{ dotfiles_toolbox_dir }}"
    version: "{{ dotfiles_toolbox_version }}"
  when: not toolbox_repo.before

- name: Extract dotfile names from config_files dir
  ansible.builtin.find:
    paths: "{{ dotfiles_toolbox_dir }}/config_files/dotfiles"
    file_type: any
    hidden: true
  register: general_config_files

- name: Create symlinks for files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/{{ item.path | basename }}"
    state: link
    force: true
    mode: "0644"
  loop: "{{ general_config_files.files }}"
