---
- name: Extract dotfile names from config_files
  ansible.builtin.find:
    paths: "{{ toolbox_dir }}/config_files/dotfiles"
    file_type: any
    hidden: true
  register: general_config_files

- name: Create symlinks for files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/{{ item.path | basename }}"
    state: link
    force: true
    mode: "0644"
  loop: "{{ general_config_files.files }}"
