export PATH=$HOME/bin:/usr/local/bin:$PATH
export FZF_BASE='$HOME/.fzf/bin/fzf'
export FZF_DEFAULT_OPTS='--cycle --layout=reverse --border --height=90% --preview="head -$LINES {}" --preview-window=nowrap --marker="*"'

export ZSH=$HOME/.oh-my-zsh
# source $ZSH/oh-my-zsh.sh

ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_UPDATE="true"

plugins=(
    git
    forgit
    fzf
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh

# ctrl+space accepts the suggestion
bindkey '^ ' autosuggest-accept

bindkey -M emacs '^ff' fzf-file-widget
bindkey -M vicmd '^ff' fzf-file-widget
bindkey -M viins '^ff' fzf-file-widget