- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - git
      - unzip
      - gnupg
      - acl
    state: present
    update_cache: true

- name: Add Hashicorp apt key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Hashicorp apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install Hashicorp packages
  become: true
  ansible.builtin.apt:
    name: "{{ hashicorp_tools }}"
    state: present
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
