---
- name: Download FZF via git
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    version: "{{ fzf_version }}"
    dest: "{{ fzf_root }}"
    depth: 1
    update: false

- name: Run fzf installation script
  ansible.builtin.command:
    cmd: "{{ fzf_root }}/install"
    creates: "{{ fzf_bin }}"
