---
# golang
golang_version: '1.21.8'
golang_platform: 'linux-arm64'
golang_packages:
  - name: github.com/amonks/run/cmd/run@latest
  - name: github.com/charmbracelet/glow@latest
  - name: github.com/charmbracelet/mods@latest
  - name: github.com/charmbracelet/skate@latest
golang_checksums:
  '1.21.8':
    linux-amd64: 'sha256:538b3b143dc7f32b093c8ffe0e050c260b57fc9d57a12c4140a639a8dd2b4e4f'
    linux-arm64: 'sha256:3c19113c686ffa142e9159de1594c952dee64d5464965142d222eab3a81f1270'