##########################
#   System Configuration
##########################
clean: false

ansible_user: "{{ lookup('env', 'HOME') | basename }}"
home_dir: "{{ lookup('env', 'HOME') }}"
toolbox_dir: "{{ home_dir }}/github.com/ecshreve/toolbox"

dirs_to_own:
  - "{{ home_dir }}/.config"
  - "{{ go_root }}"

##########################
# Packages
##########################

# Ubuntu - Debian
apt_packages:
  - zsh
  - tmux
  - eza
  - bat
  - fd-find
  - ripgrep
  - git
  - direnv
symlinks:
  bat: /usr/bin/batcat
  fd: /usr/bin/fdfind

# MacOS - Darwin
base_packages:
  - zsh
  - tmux
  - eza
  - bat
  - fd
  - ripgrep
  - git
  - gnutar
