---
- name: Configure local environment
  hosts: localhost
  connection: local
  vars_files:
    - config_vars.yml
  roles:
    - base
    - dotfiles
    - zsh
    - fzf
    - asdf
  post_tasks:
    - name: Install docker on linux
      ansible.builtin.include_role:
        name: docker
      when: ansible_os_family | lower == 'debian'
      ignore_errors: "{{ ansible_check_mode }}"
