---
- name: Prepare multipass vm
  hosts: localhost
  connection: local
  roles:
    - multipass
  vars:
    multipass_vm_name: devbox

- name: Provision with toolbox roles
  hosts: "{{ multipass_vm_name }}"
  roles:
    - base
    - dotfiles
    - zsh
    - fzf
    - asdf
    - docker
  vars:
    multipass_vm_name: devbox
    asdf_manage_apps: true
    asdf_install_app_versions:
      nodejs: "20.18.0"
      golang: "1.23.3"
      python: "3.11.9"
  ignore_errors: "{{ ansible_check_mode }}"
