---
- name: Prepare multipass vm
  hosts: localhost
  connection: local
  tasks:
    - name: Create a Multipass VM
      theko2fi.multipass.multipass_vm:
        name: devbox
        cloud_init: files/userdata.cfg
        cpus: 4
        memory: 8G
        disk: 10G
        image: noble
        state: started
      register: multipass_vm

    - name: Add the VM to the inventory
      ansible.builtin.add_host:
        name: devbox
        ansible_host: "{{ multipass_vm.result.info.devbox.ipv4[0] }}"
        ansible_connection: ssh
        ansible_python_interpreter: '/usr/bin/python3'
        ansible_user: eric

- name: Provision with toolbox roles
  hosts: devbox
  roles:
    - base
    - dotfiles
    - zsh
    - fzf
    - asdf
    - docker
  vars_files:
    - config_vars.yml
  vars:
    asdf_manage_apps: true
    asdf_install_app_versions:
      nodejs: "20.18.0"
      golang: "1.23.3"
      python: "3.11.9"
  ignore_errors: "{{ ansible_check_mode }}"
