---
- name: Configure system
  tags: system
  hosts: localhost
  vars_files:
    - vars/system.yml
    - vars/zshell.yml
  roles:
    - shell
  vars:
    clean: false
    fzf_install: true
    omz_install: true

- name: Configure Go environment
  tags: golang
  become: true
  hosts: localhost
  roles:
    - golang
  vars_files:
    - vars/golang.yml
  vars:
    clean: false
    go_version_target: 1.22.2
