---
- name: Configure shell development environment
  hosts: localhost
  roles:
    - shell
  vars:
    clean_install: false

- name: Copy dotfiles to home directory
  hosts: localhost
  roles:
    - config
  vars:
    dotfiles:
      zshrc: $HOME/.zshrc
      p10k.zsh: $HOME/.p10k.zsh
      mods.yml: $HOME/.config/mods/mods.yml

- name: Configure Go for development
  hosts: localhost
  become: true
  roles:
    - golang
  vars:
    clean_install: false
    go_version: "1.21.8"
    go_platform: linux
    go_arch: arm64
    go_tarball: go{{ go_version }}.{{ go_platform }}-{{ go_arch }}.tar.gz
    go_download_url: https://dl.google.com/go/{{ go_tarball }}
    go_checksum: '3c19113c686ffa142e9159de1594c952dee64d5464965142d222eab3a81f1270'
    go_root: "{{ ansible_GOROOT }}"
    go_packages:
      run: github.com/amonks/run/cmd/run@latest
      glow: github.com/charmbracelet/glow@latest
      mods: github.com/charmbracelet/mods@latest
      skate: github.com/charmbracelet/skate@latest
      gum: github.com/charmbracelet/gum@latest
      freeze: github.com/charmbracelet/freeze@latest
