---
- name: Configure local environment
  tags: [stable]
  hosts: localhost
  connection: local
  vars_files:
    - config_vars.yml
  roles:
    - base
    - zsh
    - fzf
    - dotfiles
    - asdf
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure local multipass instance
  tags: [dev]
  hosts: localbox
  roles:
    - base
    - zsh
    - fzf
    - dotfiles
    - asdf
  vars_files:
    - config_vars.yml
  ignore_errors: "{{ ansible_check_mode }}"
