---
# - name: Configure local environment
#   tags: [stable]
#   hosts: localhost
#   connection: local
#   vars_files:
#     - config_vars.yml
#   roles:
#     - base
#     - zsh
#     - fzf
#     - dotfiles
#     - asdf
#   ignore_errors: "{{ ansible_check_mode }}"

# - name: Configure ubuntu desktop
#   tags: [dev]
#   hosts: tpad
#   roles:
#     # - base
#     # - zsh
#     # - fzf
#     # - dotfiles
#     - asdf
#     # - docker
#   vars_files:
#     - config_vars.yml
#   ignore_errors: "{{ ansible_check_mode }}"

- name: Configure ubuntu multipass
  tags: [dev]
  hosts: multipass
  roles:
    # - base
    # - dotfiles
    # - zsh
    # - fzf
    # - asdf
    # - docker
  vars_files:
    - config_vars.yml
  tasks:
    - name: Set login shell to zsh
      ansible.builtin.user:
        name: eric
        shell: /bin/zsh
      become: true
  ignore_errors: "{{ ansible_check_mode }}"
