---
- name: Configure environment
  tags: [stable, base]
  hosts: localhost
  connection: local
  vars_files:
    - config_vars.yml
  roles:
    - base
    - zsh
    - fzf
    - dotfiles
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure asdf
  tags: [dev]
  hosts: localhost
  connection: local
  roles:
    - asdf
  vars_files:
    - config_vars.yml