---
- name: Configure shell development environment
  tags: shell
  hosts: localhost
  roles:
    - shell
  vars:
    clean: false
    apt_packages:
      - zsh
      - tmux
      - exa
      - bat
      - fd-find
      - ripgrep
      - git
    symlinks:
      bat: /usr/bin/batcat
      fd: /usr/bin/fdfind
    fzf_install: true
    omz_install: true
    omz_root: "{{ home_dir }}/.oh-my-zsh"
    omz_version: 8e088ded8289a9db2a9f2c03cab618d6dd017dd7
    p10k_version: 35833ea15f14b71dbcebc7e54c104d8d56ca5268
    omz_plugins:
      - repo: "zsh-users/zsh-autosuggestions"
        version: a411ef3e0992d4839f0732ebeb9823024afaaaa8
      - repo: "zsh-users/zsh-syntax-highlighting"
        version: db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e
      - repo: "zsh-users/zsh-completions"
        version: 67921bc12502c1e7b0f156533fbac2cb51f6943d
      - repo: "wfxr/forgit"
        version: d582f2aa0b5bf7948d78aca05c55a974e68f4884

- name: Copy dotfiles to home directory
  tags: shell
  hosts: localhost
  roles:
    - { role: dotfile, dotfile_name: .zshrc }
    - { role: dotfile, dotfile_name: .p10k.zsh }
    - { role: dotfile, dotfile_name: .tmux.conf }
    - { role: dotfile, dotfile_name: .tmux.conf.local }

- name: Configure Go environment
  tags: golang
  become: true
  hosts: localhost
  roles:
    - golang
  vars:
    clean: false
    go_version_target: "1.21.8"
    go_platform: linux
    go_arch: arm64
    go_tarball: go{{ go_version_target }}.{{ go_platform }}-{{ go_arch }}.tar.gz
    go_download_url: https://dl.google.com/go/{{ go_tarball }}
    go_checksum: '3c19113c686ffa142e9159de1594c952dee64d5464965142d222eab3a81f1270'
    go_packages:
      run: github.com/amonks/run/cmd/run@latest
      glow: github.com/charmbracelet/glow@latest
      mods: github.com/charmbracelet/mods@latest
      skate: github.com/charmbracelet/skate@latest
      gum: github.com/charmbracelet/gum@latest
      freeze: github.com/charmbracelet/freeze@latest
