---
- name: Extract git config files from config_files
  ansible.builtin.find:
    paths: "{{ toolbox_dir }}/config_files/gitenv"
    file_type: any
    hidden: true
  register: git_config_files

- name: Remove file if one is being linked
  ansible.builtin.file:
    path: "{{ home_dir }}/{{ item.path | basename }}"
    state: absent
  loop: "{{ git_config_files.files }}"
  when: not ansible_check_mode

- name: Create symlinks for files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/{{ item.path | basename }}"
    state: link
    force: true # This will replace the link if it already exists
    mode: "0644"
  loop: "{{ git_config_files.files }}"
