name: build

on:
  workflow_call: 
    

env:
  IMAGE_NAME: ghcr.io/ecshreve/toolbox
  DEV_IMAGE_NAME: ghcr.io/ecshreve/toolbox-dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  devcontainer:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - name: Install devcontainer cli
          run: npm install -g @devcontainers/cli

        - name: Build devcontainer
          run: devcontainer build --image-name ${{ env.DEV_IMAGE_NAME }}:latest --workspace-folder . --cache-to type=gha,mode=max --cache-from type=gha