name: build

on:
  pull_request: 
    branches:
      - main
  release: 
    types: [published]

env:
  IMAGE_NAME: ghcr.io/ecshreve/toolbox
  DEV_IMAGE_NAME: ghcr.io/ecshreve/toolbox-dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker tags
        id: tag-docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Set up devcontainer tags
        id: tag-devcontainer
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tag-docker.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.DEV_IMAGE_NAME }}
          cacheFrom: ${{ env.DEV_IMAGE_NAME }}
          imageTag: ${{ steps.tag-devcontainer.outputs.tags }}
          push: always
