name: ci

on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  LATEST_TAG: ghcr.io/ecshreve/toolbox:latest
  IMAGE_NAME: ghcr.io/ecshreve/toolbox

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      vtag: ${{ steps.set-docker-tag.outputs.vtag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up docker tags
        id: tag-docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,latest

      - name: Tag and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tag-docker.outputs.tags }}
          labels: ${{ steps.tag-docker.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false
      
      - name: Set docker tag output
        id: set-docker-tag
        run: |
          vtag=${{ github.ref_name }}
          if [[ $vtag != 'main' ]]; then
            $vtag=${vtag:1}
          fi
          echo vtag=$vtag >> $GITHUB_OUTPUT

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/tags/v*.*.*'
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.build.outputs.vtag }}
