name: ci

on:
  pull_request: 
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ghcr.io/ecshreve/toolbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false

      - name: Prebuild devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}-dev
          cacheFrom: ${{ env.IMAGE_NAME }}-dev
          configFile: .devcontainer/toolbox-dev/devcontainer.json
          push: always

      - name: Push devcontainer release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag ${{ env.IMAGE_NAME }}-dev:latest ${{ env.IMAGE_NAME }}-dev:${{ github.ref_name }}
          docker push ${{ env.IMAGE_NAME }}-dev:${{ github.ref_name }}
  
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.ref_name }}

