name: ci

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ghcr.io/ecshreve/toolbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ecshreve/toolbox
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          provenance: false
          cache-from: type=registry,ref=ghcr.io/ecshreve/toolbox:latest
          cache-to: type=inline

      - name: Prebuild devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ecshreve/toolbox-dev
          cacheFrom: ghcr.io/ecshreve/toolbox-dev
          configFile: .devcontainer/toolbox-dev/devcontainer.json
          push: always
     
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_CUSTOM_PAT }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            Dockerfile
            .devcontainer/toolbox-dev/devcontainer.json
          body: |
            ## info
            
            ![toolbox](https://img.shields.io/badge/toolbox-${{ github.ref_name }}-purple)
