name: devcontainer-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ecshreve/toolbox-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prebuild ${{ env.IMAGE_NAME }} image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ env.IMAGE_NAME }}
          cacheFrom: ghcr.io/${{ env.IMAGE_NAME }}
          push: filter
          refFilterForPush: 'refs/heads/main'  