name: ci

on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main

env:
  LATEST_TAG: ghcr.io/ecshreve/toolbox:latest
  IMAGE_NAME: ghcr.io/ecshreve/toolbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up docker labels
        id: meta
        uses: docker/metadata-action@v5

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ env.LATEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false

      - name: Build devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}-dev
          cacheFrom: ${{ env.IMAGE_NAME }}-dev
          configFile: .devcontainer/toolbox-dev/devcontainer.json
          push: filter
          eventFilterForPush: push
