name: devcontainer
on:
  push:
    branches: [main]
  release:
    types: [published]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: toolbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ env.IMAGE_NAME }} image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ecshreve/${{ env.IMAGE_NAME }}
          imageTag: latest,${{github.ref_name}}
          push: filter
          eventFilterForPush: release
          platform: linux/amd64,linux/arm64