name: Devcontainer Build
on:
  push:
    branches:
      - main
    tags:
      - '*'


jobs:
  build-only:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
        -
          name: Checkout
          id: checkout
          uses: actions/checkout@v1
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        -
          name: Build without pushing
          uses: devcontainers/ci@v0.3
          with:
            imageName: ghcr.io/${{ github.repository }}
            imageTag: latest,${{github.ref_name}}
            cacheFrom: ghcr.io/${{ github.repository }}
        
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
        -
          name: Checkout
          id: checkout
          uses: actions/checkout@v1
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        -
          name: Pre-build dev container image and push
          if: ${{ startsWith(github.ref, 'refs/tags/') }}
          uses: devcontainers/ci@v0.3
          with:
            imageName: ghcr.io/${{ github.repository }}
            imageTag: latest,${{github.ref_name}}
            cacheFrom: ghcr.io/${{ github.repository }}
            push: true
